// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbYml45I2Qh3-1rwmFXbL9B4XYVsHTa0',
    appId: '1:168489316917:web:b1480a230189771d53777c',
    messagingSenderId: '168489316917',
    projectId: 'groub-chat-5f0d6',
    authDomain: 'groub-chat-5f0d6.firebaseapp.com',
    storageBucket: 'groub-chat-5f0d6.firebasestorage.app',
    measurementId: 'G-2Q50QJVC70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBsdkgtuEaHHiaCCb4Dk2ZZjrIxlo5EY',
    appId: '1:168489316917:android:f6e697241832147753777c',
    messagingSenderId: '168489316917',
    projectId: 'groub-chat-5f0d6',
    storageBucket: 'groub-chat-5f0d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wcLqNiZYVDSlpppvkiL935UaRW6WiD4',
    appId: '1:168489316917:ios:0db62aad801d862153777c',
    messagingSenderId: '168489316917',
    projectId: 'groub-chat-5f0d6',
    storageBucket: 'groub-chat-5f0d6.firebasestorage.app',
    iosBundleId: 'com.example.groubChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3wcLqNiZYVDSlpppvkiL935UaRW6WiD4',
    appId: '1:168489316917:ios:0db62aad801d862153777c',
    messagingSenderId: '168489316917',
    projectId: 'groub-chat-5f0d6',
    storageBucket: 'groub-chat-5f0d6.firebasestorage.app',
    iosBundleId: 'com.example.groubChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCbYml45I2Qh3-1rwmFXbL9B4XYVsHTa0',
    appId: '1:168489316917:web:6405ad088819c64053777c',
    messagingSenderId: '168489316917',
    projectId: 'groub-chat-5f0d6',
    authDomain: 'groub-chat-5f0d6.firebaseapp.com',
    storageBucket: 'groub-chat-5f0d6.firebasestorage.app',
    measurementId: 'G-FD7Z4CZ5FT',
  );
}
